"""New IVR Log

Revision ID: 1af0345f0188
Revises: a334bbb30ab9
Create Date: 2018-03-17 07:06:34.815552

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1af0345f0188"
down_revision = "a334bbb30ab9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ivrlog",
        sa.Column("log_id", sa.String(length=80), nullable=False),
        sa.Column("log_dtime", sa.DateTime(), nullable=True),
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("member_id", sa.String(length=45), nullable=False),
        sa.Column("item_id", sa.String(length=12), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id", "member_id"],
            ["member.group_id", "member.member_id"],
            name=op.f("fk_ivrlog_group_id_member"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["menuitem.item_id"], name=op.f("fk_ivrlog_item_id_menuitem")
        ),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_ivrlog")),
    )
    op.create_index(
        "fk_ivrlog_member1_idx", "ivrlog", ["group_id", "member_id"], unique=False
    )
    op.create_index(op.f("ix_ivrlog_item_id"), "ivrlog", ["item_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ivrlog_item_id"), table_name="ivrlog")
    op.drop_index("fk_ivrlog_member1_idx", table_name="ivrlog")
    op.drop_table("ivrlog")
    # ### end Alembic commands ###
