"""New Response

Revision ID: 3ddea4ea673b
Revises: 6c6e806022e6
Create Date: 2018-03-17 07:04:39.652670

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3ddea4ea673b"
down_revision = "6c6e806022e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "response",
        sa.Column("item_id", sa.String(length=12), nullable=False),
        sa.Column("resp_num", sa.Integer(), nullable=False),
        sa.Column("target_item", sa.String(length=12), nullable=False),
        sa.Column("resp_default", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["menuitem.item_id"],
            name=op.f("fk_response_item_id_menuitem"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_item"],
            ["menuitem.item_id"],
            name=op.f("fk_response_target_item_menuitem"),
        ),
        sa.PrimaryKeyConstraint("item_id", "resp_num", name=op.f("pk_response")),
    )
    op.create_index(
        op.f("ix_response_target_item"), "response", ["target_item"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_response_target_item"), table_name="response")
    op.drop_table("response")
    # ### end Alembic commands ###
