"""Set menu to Groups

Revision ID: 41e14ace132a
Revises: d2d447ba5108
Create Date: 2018-03-17 07:28:37.899619

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "41e14ace132a"
down_revision = "d2d447ba5108"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("advgroup", sa.Column("menu_id", sa.String(length=12), nullable=True))
    op.create_index(op.f("ix_advgroup_menu_id"), "advgroup", ["menu_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_advgroup_menu_id_ivrmenu"),
        "advgroup",
        "ivrmenu",
        ["menu_id"],
        ["menu_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_advgroup_menu_id_ivrmenu"), "advgroup", type_="foreignkey"
    )
    op.drop_index(op.f("ix_advgroup_menu_id"), table_name="advgroup")
    op.drop_column("advgroup", "menu_id")
    # ### end Alembic commands ###
