"""Remove table language

Revision ID: 5abbe7a4d3e7
Revises: ee307ba34f2d
Create Date: 2020-12-09 15:25:38.929041

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5abbe7a4d3e7"
down_revision = "ee307ba34f2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("language")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "language",
        sa.Column("language_code", mysql.VARCHAR(length=4), nullable=False),
        sa.Column("language_name", mysql.VARCHAR(length=120), nullable=True),
        sa.Column("audio_id", mysql.VARCHAR(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"], ["audio.audio_id"], name="fk_language_audio_id_audio"
        ),
        sa.PrimaryKeyConstraint("language_code"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_language_audio_id", "language", ["audio_id"], unique=False)
    # ### end Alembic commands ###
