"""Few changes

Revision ID: 730d7652c632
Revises: e5c7080dd9e0
Create Date: 2018-03-05 15:10:10.551165

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "730d7652c632"
down_revision = "e5c7080dd9e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "question",
        "question_dtime",
        existing_type=mysql.VARCHAR(length=45),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "question",
        "question_dtime",
        existing_type=sa.DateTime(),
        type_=mysql.VARCHAR(length=45),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
