"""Old version Menu welcome

Revision ID: 7b71c5a627b1
Revises: a9816c26ba30
Create Date: 2018-03-17 06:42:03.239451

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7b71c5a627b1"
down_revision = "a9816c26ba30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("menuwelcome")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menuwelcome",
        sa.Column("group_id", mysql.VARCHAR(length=12), nullable=False),
        sa.Column("menu_id", mysql.VARCHAR(length=12), nullable=False),
        sa.Column("language_code", mysql.VARCHAR(length=4), nullable=False),
        sa.Column("audio_id", mysql.VARCHAR(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"], ["audio.audio_id"], name="fk_menuwelcome_audio_id_audio"
        ),
        sa.ForeignKeyConstraint(
            ["group_id", "menu_id"],
            ["ivrmenu.group_id", "ivrmenu.menu_id"],
            name="fk_menuwelcome_group_id_ivrmenu",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["language.language_code"],
            name="fk_menuwelcome_language_code_language",
        ),
        sa.PrimaryKeyConstraint("group_id", "menu_id", "language_code"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
