"""Remove itemaudio

Revision ID: 82b47b2bd55a
Revises: be86c6f600f6
Create Date: 2020-12-09 15:40:10.721518

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "82b47b2bd55a"
down_revision = "be86c6f600f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("itemaudio")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "itemaudio",
        sa.Column("item_id", mysql.VARCHAR(length=12), nullable=False),
        sa.Column("audio_id", mysql.VARCHAR(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"], ["audio.audio_id"], name="fk_itemaudio_audio_id_audio"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["menuitem.item_id"],
            name="fk_itemaudio_item_id_menuitem",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("item_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_itemaudio_audio_id", "itemaudio", ["audio_id"], unique=False)
    # ### end Alembic commands ###
