"""Add telephone to the users

Revision ID: 9268c216b998
Revises: f9cc74084755
Create Date: 2018-03-16 13:43:19.661000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9268c216b998"
down_revision = "f9cc74084755"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("user_telef", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "user_telef")
    # ### end Alembic commands ###
