"""Add tags to questions

Revision ID: 9f139eb87d3e
Revises: b6cae160fc38
Create Date: 2018-03-18 07:17:04.450128

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9f139eb87d3e"
down_revision = "b6cae160fc38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question", sa.Column("question_tags", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "question_tags")
    # ### end Alembic commands ###
