"""New Item audio

Revision ID: a334bbb30ab9
Revises: 3ddea4ea673b
Create Date: 2018-03-17 07:05:50.072350

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a334bbb30ab9"
down_revision = "3ddea4ea673b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "itemaudio",
        sa.Column("item_id", sa.String(length=12), nullable=False),
        sa.Column("language_code", sa.String(length=4), nullable=False),
        sa.Column("audio_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"], ["audio.audio_id"], name=op.f("fk_itemaudio_audio_id_audio")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["menuitem.item_id"],
            name=op.f("fk_itemaudio_item_id_menuitem"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["language.language_code"],
            name=op.f("fk_itemaudio_language_code_language"),
        ),
        sa.PrimaryKeyConstraint("item_id", "language_code", name=op.f("pk_itemaudio")),
    )
    op.create_index(
        op.f("ix_itemaudio_audio_id"), "itemaudio", ["audio_id"], unique=False
    )
    op.create_index(
        op.f("ix_itemaudio_language_code"), "itemaudio", ["language_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_itemaudio_language_code"), table_name="itemaudio")
    op.drop_index(op.f("ix_itemaudio_audio_id"), table_name="itemaudio")
    op.drop_table("itemaudio")
    # ### end Alembic commands ###
