"""Add active group

Revision ID: b1655956bdc9
Revises: e712ba8aefeb
Create Date: 2018-07-04 11:06:50.544208

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b1655956bdc9"
down_revision = "e712ba8aefeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groupuser", sa.Column("group_active", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groupuser", "group_active")
    # ### end Alembic commands ###
