"""Old version Response

Revision ID: b8c6b83d1377
Revises: ffe2c0e5a300
Create Date: 2018-03-17 06:37:07.817156

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b8c6b83d1377"
down_revision = "ffe2c0e5a300"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("response")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "response",
        sa.Column("item_id", mysql.VARCHAR(length=12), nullable=False),
        sa.Column(
            "resp_num",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("target_item", mysql.VARCHAR(length=12), nullable=False),
        sa.Column(
            "resp_default",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["menuitem.item_id"],
            name="fk_response_item_id_menuitem",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_item"],
            ["menuitem.item_id"],
            name="fk_response_target_item_menuitem",
        ),
        sa.PrimaryKeyConstraint("item_id", "resp_num"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
