"""Initial database structure

Revision ID: ba2da32f14f4
Revises: 
Create Date: 2018-02-23 10:49:48.807293

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ba2da32f14f4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "county",
        sa.Column("county_id", sa.String(length=12), nullable=False),
        sa.Column("county_name", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("county_id", name=op.f("pk_county")),
    )
    op.create_table(
        "subcounty",
        sa.Column("county_id", sa.String(length=12), nullable=False),
        sa.Column("subcounty_id", sa.String(length=12), nullable=False),
        sa.Column("subcounty_name", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["county_id"],
            ["county.county_id"],
            name=op.f("fk_subcounty_county_id_county"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("county_id", "subcounty_id", name=op.f("pk_subcounty")),
    )
    op.create_table(
        "advgroup",
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("group_name", sa.String(length=120), nullable=True),
        sa.Column("group_ward", sa.String(length=120), nullable=True),
        sa.Column("group_lat", sa.String(length=80), nullable=True),
        sa.Column("group_long", sa.String(length=180), nullable=True),
        sa.Column("group_elev", sa.Numeric(precision=11, scale=3), nullable=True),
        sa.Column("county_id", sa.String(length=12), nullable=False),
        sa.Column("subcounty_id", sa.String(length=12), nullable=False),
        sa.ForeignKeyConstraint(
            ["county_id", "subcounty_id"],
            ["subcounty.county_id", "subcounty.subcounty_id"],
            name=op.f("fk_advgroup_county_id_subcounty"),
        ),
        sa.PrimaryKeyConstraint("group_id", name=op.f("pk_advgroup")),
    )
    op.create_index(
        "fk_advgroup_subcounty1_idx",
        "advgroup",
        ["county_id", "subcounty_id"],
        unique=False,
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.String(length=120), nullable=False),
        sa.Column("user_name", sa.String(length=45), nullable=True),
        sa.Column("user_pass", sa.String(length=120), nullable=True),
        sa.Column("user_active", sa.Integer(), nullable=True),
        sa.Column("user_admin", sa.Integer(), nullable=True),
        sa.Column("county_id", sa.String(length=12), nullable=True),
        sa.Column("subcounty_id", sa.String(length=12), nullable=True),
        sa.ForeignKeyConstraint(
            ["county_id", "subcounty_id"],
            ["subcounty.county_id", "subcounty.subcounty_id"],
            name=op.f("fk_user_county_id_subcounty"),
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user")),
    )
    op.create_index(
        "fk_user_subcounty1_idx", "user", ["county_id", "subcounty_id"], unique=False
    )
    op.create_table(
        "answer",
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("answer_id", sa.String(length=12), nullable=False),
        sa.Column("user_id", sa.String(length=120), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("answer_votes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["advgroup.group_id"],
            name=op.f("fk_answer_group_id_advgroup"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.user_id"], name=op.f("fk_answer_user_id_user")
        ),
        sa.PrimaryKeyConstraint("group_id", "answer_id", name=op.f("pk_answer")),
    )
    op.create_index(op.f("ix_answer_group_id"), "answer", ["group_id"], unique=False)
    op.create_index(op.f("ix_answer_user_id"), "answer", ["user_id"], unique=False)
    op.create_table(
        "audio",
        sa.Column("audio_id", sa.String(length=80), nullable=False),
        sa.Column("audio_desc", sa.String(length=120), nullable=True),
        sa.Column("audio_file", sa.Text(), nullable=True),
        sa.Column("group_id", sa.String(length=12), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["advgroup.group_id"],
            name=op.f("fk_audio_group_id_advgroup"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("audio_id", name=op.f("pk_audio")),
    )
    op.create_index(op.f("ix_audio_group_id"), "audio", ["group_id"], unique=False)
    op.create_table(
        "groupuser",
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("user_id", sa.String(length=120), nullable=False),
        sa.Column("access_type", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["advgroup.group_id"],
            name=op.f("fk_groupuser_group_id_advgroup"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
            name=op.f("fk_groupuser_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id", name=op.f("pk_groupuser")),
    )
    op.create_index(
        op.f("ix_groupuser_user_id"), "groupuser", ["user_id"], unique=False
    )
    op.create_table(
        "ivrmenu",
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("menu_id", sa.String(length=12), nullable=False),
        sa.Column("menu_name", sa.String(length=45), nullable=True),
        sa.Column("menu_current", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["advgroup.group_id"],
            name=op.f("fk_ivrmenu_group_id_advgroup"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "menu_id", name=op.f("pk_ivrmenu")),
    )
    op.create_table(
        "member",
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("member_id", sa.String(length=45), nullable=False),
        sa.Column("member_name", sa.String(length=120), nullable=True),
        sa.Column("member_tele", sa.String(length=45), nullable=True),
        sa.Column("member_gender", sa.Integer(), nullable=True),
        sa.Column("member_village", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["advgroup.group_id"],
            name=op.f("fk_member_group_id_advgroup"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "member_id", name=op.f("pk_member")),
    )
    op.create_table(
        "answeraudio",
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("answer_id", sa.String(length=12), nullable=False),
        sa.Column("audio_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"], ["audio.audio_id"], name=op.f("fk_answeraudio_audio_id_audio")
        ),
        sa.ForeignKeyConstraint(
            ["group_id", "answer_id"],
            ["answer.group_id", "answer.answer_id"],
            name=op.f("fk_answeraudio_group_id_answer"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "group_id", "answer_id", "audio_id", name=op.f("pk_answeraudio")
        ),
    )
    op.create_index(
        op.f("ix_answeraudio_audio_id"), "answeraudio", ["audio_id"], unique=False
    )
    op.create_table(
        "language",
        sa.Column("language_code", sa.String(length=4), nullable=False),
        sa.Column("language_name", sa.String(length=120), nullable=True),
        sa.Column("audio_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"], ["audio.audio_id"], name=op.f("fk_language_audio_id_audio")
        ),
        sa.PrimaryKeyConstraint("language_code", name=op.f("pk_language")),
    )
    op.create_index(
        op.f("ix_language_audio_id"), "language", ["audio_id"], unique=False
    )
    op.create_table(
        "menuitem",
        sa.Column("item_id", sa.String(length=12), nullable=False),
        sa.Column("item_type", sa.Integer(), nullable=True),
        sa.Column("item_desc", sa.String(length=45), nullable=True),
        sa.Column("item_pos", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("menu_id", sa.String(length=12), nullable=False),
        sa.Column("next_item", sa.String(length=12), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id", "menu_id"],
            ["ivrmenu.group_id", "ivrmenu.menu_id"],
            name=op.f("fk_menuitem_group_id_ivrmenu"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["next_item"],
            ["menuitem.item_id"],
            name=op.f("fk_menuitem_next_item_menuitem"),
        ),
        sa.PrimaryKeyConstraint("item_id", name=op.f("pk_menuitem")),
    )
    op.create_index(
        "fk_menuitem_ivrmenu1_idx", "menuitem", ["group_id", "menu_id"], unique=False
    )
    op.create_index(
        op.f("ix_menuitem_next_item"), "menuitem", ["next_item"], unique=False
    )
    op.create_table(
        "question",
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("member_id", sa.String(length=45), nullable=False),
        sa.Column("question_id", sa.String(length=12), nullable=False),
        sa.Column("question_dtime", sa.String(length=45), nullable=True),
        sa.Column("question_audiofile", sa.Text(), nullable=True),
        sa.Column("question_text", sa.Text(), nullable=True),
        sa.Column("question_status", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id", "member_id"],
            ["member.group_id", "member.member_id"],
            name=op.f("fk_question_group_id_member"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "group_id", "member_id", "question_id", name=op.f("pk_question")
        ),
    )
    op.create_table(
        "itemaudio",
        sa.Column("item_id", sa.String(length=12), nullable=False),
        sa.Column("language_code", sa.String(length=4), nullable=False),
        sa.Column("audio_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"], ["audio.audio_id"], name=op.f("fk_itemaudio_audio_id_audio")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["menuitem.item_id"],
            name=op.f("fk_itemaudio_item_id_menuitem"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["language.language_code"],
            name=op.f("fk_itemaudio_language_code_language"),
        ),
        sa.PrimaryKeyConstraint("item_id", "language_code", name=op.f("pk_itemaudio")),
    )
    op.create_index(
        op.f("ix_itemaudio_audio_id"), "itemaudio", ["audio_id"], unique=False
    )
    op.create_index(
        op.f("ix_itemaudio_language_code"), "itemaudio", ["language_code"], unique=False
    )
    op.create_table(
        "ivrlog",
        sa.Column("log_id", sa.String(length=80), nullable=False),
        sa.Column("log_dtime", sa.DateTime(), nullable=True),
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("member_id", sa.String(length=45), nullable=False),
        sa.Column("item_id", sa.String(length=12), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id", "member_id"],
            ["member.group_id", "member.member_id"],
            name=op.f("fk_ivrlog_group_id_member"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["menuitem.item_id"], name=op.f("fk_ivrlog_item_id_menuitem")
        ),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_ivrlog")),
    )
    op.create_index(
        "fk_ivrlog_member1_idx", "ivrlog", ["group_id", "member_id"], unique=False
    )
    op.create_index(op.f("ix_ivrlog_item_id"), "ivrlog", ["item_id"], unique=False)
    op.create_table(
        "menuwelcome",
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("menu_id", sa.String(length=12), nullable=False),
        sa.Column("language_code", sa.String(length=4), nullable=False),
        sa.Column("audio_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"], ["audio.audio_id"], name=op.f("fk_menuwelcome_audio_id_audio")
        ),
        sa.ForeignKeyConstraint(
            ["group_id", "menu_id"],
            ["ivrmenu.group_id", "ivrmenu.menu_id"],
            name=op.f("fk_menuwelcome_group_id_ivrmenu"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["language.language_code"],
            name=op.f("fk_menuwelcome_language_code_language"),
        ),
        sa.PrimaryKeyConstraint(
            "group_id", "menu_id", "language_code", name=op.f("pk_menuwelcome")
        ),
    )
    op.create_index(
        op.f("ix_menuwelcome_audio_id"), "menuwelcome", ["audio_id"], unique=False
    )
    op.create_index(
        op.f("ix_menuwelcome_language_code"),
        "menuwelcome",
        ["language_code"],
        unique=False,
    )
    op.create_table(
        "questionanswer",
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("member_id", sa.String(length=45), nullable=False),
        sa.Column("question_id", sa.String(length=12), nullable=False),
        sa.Column("answer_group", sa.String(length=12), nullable=False),
        sa.Column("answer_id", sa.String(length=12), nullable=False),
        sa.Column("answer_sent", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["answer_group", "answer_id"],
            ["answer.group_id", "answer.answer_id"],
            name=op.f("fk_questionanswer_answer_group_answer"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id", "member_id", "question_id"],
            ["question.group_id", "question.member_id", "question.question_id"],
            name=op.f("fk_questionanswer_group_id_question"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "group_id",
            "member_id",
            "question_id",
            "answer_group",
            "answer_id",
            name=op.f("pk_questionanswer"),
        ),
    )
    op.create_index(
        "fk_questionanswer_answer1_idx",
        "questionanswer",
        ["answer_group", "answer_id"],
        unique=False,
    )
    op.create_table(
        "questiontag",
        sa.Column("group_id", sa.String(length=12), nullable=False),
        sa.Column("member_id", sa.String(length=45), nullable=False),
        sa.Column("question_id", sa.String(length=12), nullable=False),
        sa.Column("tag_name", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id", "member_id", "question_id"],
            ["question.group_id", "question.member_id", "question.question_id"],
            name=op.f("fk_questiontag_group_id_question"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "group_id",
            "member_id",
            "question_id",
            "tag_name",
            name=op.f("pk_questiontag"),
        ),
    )
    op.create_table(
        "response",
        sa.Column("item_id", sa.String(length=12), nullable=False),
        sa.Column("resp_num", sa.Integer(), nullable=False),
        sa.Column("target_item", sa.String(length=12), nullable=False),
        sa.Column("resp_default", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["menuitem.item_id"],
            name=op.f("fk_response_item_id_menuitem"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_item"],
            ["menuitem.item_id"],
            name=op.f("fk_response_target_item_menuitem"),
        ),
        sa.PrimaryKeyConstraint("item_id", "resp_num", name=op.f("pk_response")),
    )
    op.create_index(
        op.f("ix_response_target_item"), "response", ["target_item"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_response_target_item"), table_name="response")
    op.drop_table("response")
    op.drop_table("questiontag")
    op.drop_index("fk_questionanswer_answer1_idx", table_name="questionanswer")
    op.drop_table("questionanswer")
    op.drop_index(op.f("ix_menuwelcome_language_code"), table_name="menuwelcome")
    op.drop_index(op.f("ix_menuwelcome_audio_id"), table_name="menuwelcome")
    op.drop_table("menuwelcome")
    op.drop_index(op.f("ix_ivrlog_item_id"), table_name="ivrlog")
    op.drop_index("fk_ivrlog_member1_idx", table_name="ivrlog")
    op.drop_table("ivrlog")
    op.drop_index(op.f("ix_itemaudio_language_code"), table_name="itemaudio")
    op.drop_index(op.f("ix_itemaudio_audio_id"), table_name="itemaudio")
    op.drop_table("itemaudio")
    op.drop_table("question")
    op.drop_index(op.f("ix_menuitem_next_item"), table_name="menuitem")
    op.drop_index("fk_menuitem_ivrmenu1_idx", table_name="menuitem")
    op.drop_table("menuitem")
    op.drop_index(op.f("ix_language_audio_id"), table_name="language")
    op.drop_table("language")
    op.drop_index(op.f("ix_answeraudio_audio_id"), table_name="answeraudio")
    op.drop_table("answeraudio")
    op.drop_table("member")
    op.drop_table("ivrmenu")
    op.drop_index(op.f("ix_groupuser_user_id"), table_name="groupuser")
    op.drop_table("groupuser")
    op.drop_index(op.f("ix_audio_group_id"), table_name="audio")
    op.drop_table("audio")
    op.drop_index(op.f("ix_answer_user_id"), table_name="answer")
    op.drop_index(op.f("ix_answer_group_id"), table_name="answer")
    op.drop_table("answer")
    op.drop_index("fk_user_subcounty1_idx", table_name="user")
    op.drop_table("user")
    op.drop_index("fk_advgroup_subcounty1_idx", table_name="advgroup")
    op.drop_table("advgroup")
    op.drop_table("subcounty")
    op.drop_table("county")
    # ### end Alembic commands ###
