"""Move audio ID from itemaudio to menuitem

Revision ID: be86c6f600f6
Revises: 5abbe7a4d3e7
Create Date: 2020-12-09 15:33:46.023755

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be86c6f600f6"
down_revision = "5abbe7a4d3e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menuitem", sa.Column("audio_id", sa.String(length=80), nullable=False)
    )
    op.create_index(
        op.f("ix_menuitem_audio_id"), "menuitem", ["audio_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_menuitem_audio_id_audio"),
        "menuitem",
        "audio",
        ["audio_id"],
        ["audio_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_menuitem_audio_id_audio"), "menuitem", type_="foreignkey"
    )
    op.drop_index(op.f("ix_menuitem_audio_id"), table_name="menuitem")
    op.drop_column("menuitem", "audio_id")
    # ### end Alembic commands ###
