"""Change gander type to string

Revision ID: c7c86f035f4d
Revises: ff9ec7e8f0dd
Create Date: 2018-07-18 20:55:14.862770

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c7c86f035f4d"
down_revision = "ff9ec7e8f0dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "member",
        "member_gardentype",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "member",
        "member_gardentype",
        existing_type=sa.String(length=32),
        type_=mysql.INTEGER(display_width=11),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
