"""Add user to audios

Revision ID: c8f224d38914
Revises: b1655956bdc9
Create Date: 2018-07-04 11:42:32.152644

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c8f224d38914"
down_revision = "b1655956bdc9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audio", sa.Column("user_id", sa.String(length=120)))
    op.create_index(op.f("ix_audio_user_id"), "audio", ["user_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_audio_user_id_user"), "audio", "user", ["user_id"], ["user_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_audio_user_id_user"), "audio", type_="foreignkey")
    op.drop_index(op.f("ix_audio_user_id"), table_name="audio")
    op.drop_column("audio", "user_id")
    # ### end Alembic commands ###
