"""Set password to text. Add API key

Revision ID: d2cbe0cde34d
Revises: 82b47b2bd55a
Create Date: 2021-04-29 10:30:42.271035

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d2cbe0cde34d"
down_revision = "82b47b2bd55a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("user_apikey", sa.String(length=64), nullable=True))
    op.alter_column(
        "user",
        "user_pass",
        existing_type=mysql.VARCHAR(length=120),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "user_pass",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=120),
        existing_nullable=True,
    )
    op.drop_column("user", "user_apikey")
    # ### end Alembic commands ###
