"""Set menu to Extension agents

Revision ID: d2d447ba5108
Revises: 1af0345f0188
Create Date: 2018-03-17 07:27:03.926588

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d2d447ba5108"
down_revision = "1af0345f0188"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("menu_id", sa.String(length=12), nullable=True))
    op.create_index(op.f("ix_user_menu_id"), "user", ["menu_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_user_menu_id_ivrmenu"), "user", "ivrmenu", ["menu_id"], ["menu_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_user_menu_id_ivrmenu"), "user", type_="foreignkey")
    op.drop_index(op.f("ix_user_menu_id"), table_name="user")
    op.drop_column("user", "menu_id")
    # ### end Alembic commands ###
