"""Add email to user

Revision ID: e5c7080dd9e0
Revises: ba2da32f14f4
Create Date: 2018-02-23 11:40:53.609183

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e5c7080dd9e0"
down_revision = "ba2da32f14f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("user_email", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "user_email")
    # ### end Alembic commands ###
