"""Add audio type

Revision ID: e712ba8aefeb
Revises: 9f139eb87d3e
Create Date: 2018-07-04 10:27:17.359691

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e712ba8aefeb"
down_revision = "9f139eb87d3e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audio", sa.Column("audio_type", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audio", "audio_type")
    # ### end Alembic commands ###
