"""New IVR menu

Revision ID: eb3de7c85dcc
Revises: 74968170c1d5
Create Date: 2018-03-17 07:01:34.118917

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eb3de7c85dcc"
down_revision = "74968170c1d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ivrmenu",
        sa.Column("menu_id", sa.String(length=12), nullable=False),
        sa.Column("menu_name", sa.String(length=45), nullable=True),
        sa.PrimaryKeyConstraint("menu_id", name=op.f("pk_ivrmenu")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ivrmenu")
    # ### end Alembic commands ###
