"""Remove language from itemaudio

Revision ID: ee307ba34f2d
Revises: ca183d2d94d3
Create Date: 2020-12-09 13:53:53.517359

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ee307ba34f2d"
down_revision = "ca183d2d94d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_itemaudio_language_code_language", "itemaudio", type_="foreignkey"
    )
    op.drop_index("ix_itemaudio_language_code", table_name="itemaudio")
    op.drop_column("itemaudio", "language_code")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "itemaudio", sa.Column("language_code", mysql.VARCHAR(length=4), nullable=False)
    )
    op.create_foreign_key(
        "fk_itemaudio_language_code_language",
        "itemaudio",
        "language",
        ["language_code"],
        ["language_code"],
    )
    op.create_index(
        "ix_itemaudio_language_code", "itemaudio", ["language_code"], unique=False
    )
    # ### end Alembic commands ###
