"""New Menu welcome

Revision ID: f10491ed9419
Revises: eb3de7c85dcc
Create Date: 2018-03-17 07:02:18.732092

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f10491ed9419"
down_revision = "eb3de7c85dcc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menuwelcome",
        sa.Column("menu_id", sa.String(length=12), nullable=False),
        sa.Column("language_code", sa.String(length=4), nullable=False),
        sa.Column("audio_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"], ["audio.audio_id"], name=op.f("fk_menuwelcome_audio_id_audio")
        ),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["language.language_code"],
            name=op.f("fk_menuwelcome_language_code_language"),
        ),
        sa.ForeignKeyConstraint(
            ["menu_id"],
            ["ivrmenu.menu_id"],
            name=op.f("fk_menuwelcome_menu_id_ivrmenu"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "menu_id", "language_code", name=op.f("pk_menuwelcome")
        ),
    )
    op.create_index(
        op.f("ix_menuwelcome_audio_id"), "menuwelcome", ["audio_id"], unique=False
    )
    op.create_index(
        op.f("ix_menuwelcome_language_code"),
        "menuwelcome",
        ["language_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_menuwelcome_menu_id"), "menuwelcome", ["menu_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_menuwelcome_menu_id"), table_name="menuwelcome")
    op.drop_index(op.f("ix_menuwelcome_language_code"), table_name="menuwelcome")
    op.drop_index(op.f("ix_menuwelcome_audio_id"), table_name="menuwelcome")
    op.drop_table("menuwelcome")
    # ### end Alembic commands ###
