"""Add audio reply

Revision ID: f1c502e88145
Revises: c8f224d38914
Create Date: 2018-07-04 21:17:05.430449

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1c502e88145"
down_revision = "c8f224d38914"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question", sa.Column("audioreply_id", sa.String(length=80), nullable=True)
    )
    op.create_index(
        op.f("ix_question_audioreply_id"), "question", ["audioreply_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_question_audioreply_id_audio"),
        "question",
        "audio",
        ["audioreply_id"],
        ["audio_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_question_audioreply_id_audio"), "question", type_="foreignkey"
    )
    op.drop_index(op.f("ix_question_audioreply_id"), table_name="question")
    op.drop_column("question", "audioreply_id")
    # ### end Alembic commands ###
