"""Add short name to the group

Revision ID: f9cc74084755
Revises: 730d7652c632
Create Date: 2018-03-15 10:30:09.290621

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f9cc74084755"
down_revision = "730d7652c632"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "advgroup", sa.Column("group_sname", sa.String(length=120), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("advgroup", "group_sname")
    # ### end Alembic commands ###
