"""Add garden type to members

Revision ID: ff9ec7e8f0dd
Revises: 3954b7abff02
Create Date: 2018-07-12 22:31:10.638234

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ff9ec7e8f0dd"
down_revision = "3954b7abff02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("member", sa.Column("member_gardentype", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("member", "member_gardentype")
    # ### end Alembic commands ###
