"""Old version Item audio

Revision ID: ffe2c0e5a300
Revises: 5af1f502ac5c
Create Date: 2018-03-17 06:34:39.844037

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ffe2c0e5a300"
down_revision = "5af1f502ac5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("itemaudio")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "itemaudio",
        sa.Column("item_id", mysql.VARCHAR(length=12), nullable=False),
        sa.Column("language_code", mysql.VARCHAR(length=4), nullable=False),
        sa.Column("audio_id", mysql.VARCHAR(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"], ["audio.audio_id"], name="fk_itemaudio_audio_id_audio"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["menuitem.item_id"],
            name="fk_itemaudio_item_id_menuitem",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["language.language_code"],
            name="fk_itemaudio_language_code_language",
        ),
        sa.PrimaryKeyConstraint("item_id", "language_code"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
