-- MySQL Script generated by MySQL Workbench
-- Sat 17 Mar 2018 06:53:44 AM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ushauri2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ushauri2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ushauri2` DEFAULT CHARACTER SET utf8 ;
USE `ushauri2` ;

-- -----------------------------------------------------
-- Table `ushauri2`.`county`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`county` (
  `county_id` VARCHAR(12) NOT NULL,
  `county_name` VARCHAR(120) NULL,
  PRIMARY KEY (`county_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Counties';


-- -----------------------------------------------------
-- Table `ushauri2`.`subcounty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`subcounty` (
  `county_id` VARCHAR(12) NOT NULL,
  `subcounty_id` VARCHAR(12) NOT NULL,
  `subcounty_name` VARCHAR(120) NULL,
  PRIMARY KEY (`county_id`, `subcounty_id`),
  CONSTRAINT `fk_subcounty_county`
    FOREIGN KEY (`county_id`)
    REFERENCES `ushauri2`.`county` (`county_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Sub-counties\n';


-- -----------------------------------------------------
-- Table `ushauri2`.`ivrmenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`ivrmenu` (
  `menu_id` VARCHAR(12) NOT NULL,
  `menu_name` VARCHAR(45) NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'IVR Menu';


-- -----------------------------------------------------
-- Table `ushauri2`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`user` (
  `user_id` VARCHAR(120) NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `user_pass` VARCHAR(120) NULL,
  `user_active` INT(1) NULL,
  `user_admin` INT(1) NULL,
  `user_email` TEXT NULL,
  `county_id` VARCHAR(12) NULL,
  `subcounty_id` VARCHAR(12) NULL,
  `user_telef` VARCHAR(120) NULL,
  `menu_id` VARCHAR(12) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_subcounty1_idx` (`county_id` ASC, `subcounty_id` ASC),
  INDEX `fk_user_ivrmenu1_idx` (`menu_id` ASC),
  CONSTRAINT `fk_user_subcounty1`
    FOREIGN KEY (`county_id` , `subcounty_id`)
    REFERENCES `ushauri2`.`subcounty` (`county_id` , `subcounty_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_ivrmenu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `ushauri2`.`ivrmenu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Users';


-- -----------------------------------------------------
-- Table `ushauri2`.`advgroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`advgroup` (
  `group_id` VARCHAR(12) NOT NULL,
  `group_name` VARCHAR(120) NULL,
  `group_ward` VARCHAR(120) NULL,
  `group_lat` VARCHAR(80) NULL,
  `group_long` VARCHAR(180) NULL,
  `group_elev` DECIMAL(11,3) NULL,
  `county_id` VARCHAR(12) NOT NULL,
  `subcounty_id` VARCHAR(12) NOT NULL,
  `group_sname` VARCHAR(120) NULL,
  `menu_id` VARCHAR(12) NULL,
  PRIMARY KEY (`group_id`),
  INDEX `fk_advgroup_subcounty1_idx` (`county_id` ASC, `subcounty_id` ASC),
  INDEX `fk_advgroup_ivrmenu1_idx` (`menu_id` ASC),
  CONSTRAINT `fk_advgroup_subcounty1`
    FOREIGN KEY (`county_id` , `subcounty_id`)
    REFERENCES `ushauri2`.`subcounty` (`county_id` , `subcounty_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_advgroup_ivrmenu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `ushauri2`.`ivrmenu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Advisory groups';


-- -----------------------------------------------------
-- Table `ushauri2`.`groupuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`groupuser` (
  `group_id` VARCHAR(12) NOT NULL,
  `user_id` VARCHAR(120) NOT NULL,
  `access_type` INT(1) NULL,
  PRIMARY KEY (`group_id`, `user_id`),
  INDEX `fk_groupmember_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_groupmember_advgroup1`
    FOREIGN KEY (`group_id`)
    REFERENCES `ushauri2`.`advgroup` (`group_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupmember_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ushauri2`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Users of a advisory group\n';


-- -----------------------------------------------------
-- Table `ushauri2`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`member` (
  `group_id` VARCHAR(12) NOT NULL,
  `member_id` VARCHAR(45) NOT NULL,
  `member_name` VARCHAR(120) NULL,
  `member_tele` VARCHAR(45) NULL,
  `member_gender` INT(1) NULL,
  `member_village` VARCHAR(120) NULL,
  PRIMARY KEY (`group_id`, `member_id`),
  CONSTRAINT `fk_member_advgroup1`
    FOREIGN KEY (`group_id`)
    REFERENCES `ushauri2`.`advgroup` (`group_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Members of a group';


-- -----------------------------------------------------
-- Table `ushauri2`.`audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`audio` (
  `audio_id` VARCHAR(80) NOT NULL,
  `audio_desc` VARCHAR(120) NULL,
  `audio_file` TEXT NULL,
  `group_id` VARCHAR(12) NULL,
  PRIMARY KEY (`audio_id`),
  INDEX `fk_audio_advgroup1_idx` (`group_id` ASC),
  CONSTRAINT `fk_audio_advgroup1`
    FOREIGN KEY (`group_id`)
    REFERENCES `ushauri2`.`advgroup` (`group_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table of audio files';


-- -----------------------------------------------------
-- Table `ushauri2`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`language` (
  `language_code` VARCHAR(4) NOT NULL,
  `language_name` VARCHAR(120) NULL,
  `audio_id` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`language_code`),
  INDEX `fk_lnaguage_audio1_idx` (`audio_id` ASC),
  CONSTRAINT `fk_lnaguage_audio1`
    FOREIGN KEY (`audio_id`)
    REFERENCES `ushauri2`.`audio` (`audio_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ushauri2`.`menuwelcome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`menuwelcome` (
  `menu_id` VARCHAR(12) NOT NULL,
  `language_code` VARCHAR(4) NOT NULL,
  `audio_id` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`menu_id`, `language_code`),
  INDEX `fk_menuwelcome_lnaguage1_idx` (`language_code` ASC),
  INDEX `fk_menuwelcome_audio1_idx` (`audio_id` ASC),
  INDEX `fk_menuwelcome_ivrmenu1_idx` (`menu_id` ASC),
  CONSTRAINT `fk_menuwelcome_lnaguage1`
    FOREIGN KEY (`language_code`)
    REFERENCES `ushauri2`.`language` (`language_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menuwelcome_audio1`
    FOREIGN KEY (`audio_id`)
    REFERENCES `ushauri2`.`audio` (`audio_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menuwelcome_ivrmenu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `ushauri2`.`ivrmenu` (`menu_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Menu welcome message';


-- -----------------------------------------------------
-- Table `ushauri2`.`menuitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`menuitem` (
  `item_id` VARCHAR(12) NOT NULL,
  `item_type` INT(1) NULL,
  `item_desc` TEXT NULL,
  `item_pos` INT(4) NULL,
  `next_item` VARCHAR(12) NULL COMMENT 'The next item if the item does not ask for responses\n',
  `menu_id` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_menuitem_menuitem1_idx` (`next_item` ASC),
  INDEX `fk_menuitem_ivrmenu1_idx` (`menu_id` ASC),
  CONSTRAINT `fk_menuitem_menuitem1`
    FOREIGN KEY (`next_item`)
    REFERENCES `ushauri2`.`menuitem` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menuitem_ivrmenu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `ushauri2`.`ivrmenu` (`menu_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ushauri2`.`response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`response` (
  `item_id` VARCHAR(12) NOT NULL,
  `resp_num` INT(11) NOT NULL,
  `target_item` VARCHAR(12) NOT NULL,
  `resp_default` INT(1) NULL COMMENT 'Default if no response is given\n',
  PRIMARY KEY (`item_id`, `resp_num`),
  INDEX `fk_response_menuitem1_idx` (`target_item` ASC),
  CONSTRAINT `fk_responses_menuitem1`
    FOREIGN KEY (`item_id`)
    REFERENCES `ushauri2`.`menuitem` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_response_menuitem1`
    FOREIGN KEY (`target_item`)
    REFERENCES `ushauri2`.`menuitem` (`item_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ushauri2`.`itemaudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`itemaudio` (
  `item_id` VARCHAR(12) NOT NULL,
  `language_code` VARCHAR(4) NOT NULL,
  `audio_id` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`item_id`, `language_code`),
  INDEX `fk_menuaudio_lnaguage1_idx` (`language_code` ASC),
  INDEX `fk_menuaudio_audio1_idx` (`audio_id` ASC),
  CONSTRAINT `fk_menuaudio_menuitem1`
    FOREIGN KEY (`item_id`)
    REFERENCES `ushauri2`.`menuitem` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menuaudio_lnaguage1`
    FOREIGN KEY (`language_code`)
    REFERENCES `ushauri2`.`language` (`language_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menuaudio_audio1`
    FOREIGN KEY (`audio_id`)
    REFERENCES `ushauri2`.`audio` (`audio_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ushauri2`.`ivrlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`ivrlog` (
  `log_id` VARCHAR(80) NOT NULL,
  `log_dtime` DATETIME NULL,
  `group_id` VARCHAR(12) NOT NULL,
  `member_id` VARCHAR(45) NOT NULL,
  `item_id` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_ivrlog_member1_idx` (`group_id` ASC, `member_id` ASC),
  INDEX `fk_ivrlog_menuitem1_idx` (`item_id` ASC),
  CONSTRAINT `fk_ivrlog_member1`
    FOREIGN KEY (`group_id` , `member_id`)
    REFERENCES `ushauri2`.`member` (`group_id` , `member_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ivrlog_menuitem1`
    FOREIGN KEY (`item_id`)
    REFERENCES `ushauri2`.`menuitem` (`item_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ushauri2`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`question` (
  `group_id` VARCHAR(12) NOT NULL,
  `member_id` VARCHAR(45) NOT NULL,
  `question_id` VARCHAR(12) NOT NULL,
  `question_dtime` VARCHAR(45) NULL,
  `question_audiofile` TEXT NULL,
  `question_text` TEXT NULL,
  `question_status` INT(1) NULL,
  PRIMARY KEY (`group_id`, `member_id`, `question_id`),
  CONSTRAINT `fk_ivrquestion_member1`
    FOREIGN KEY (`group_id` , `member_id`)
    REFERENCES `ushauri2`.`member` (`group_id` , `member_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ushauri2`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`answer` (
  `group_id` VARCHAR(12) NOT NULL,
  `answer_id` VARCHAR(12) NOT NULL,
  `user_id` VARCHAR(120) NOT NULL,
  `answer_text` TEXT NULL,
  `answer_votes` INT(11) NULL,
  PRIMARY KEY (`group_id`, `answer_id`),
  INDEX `fk_answer_advgroup1_idx` (`group_id` ASC),
  INDEX `fk_answer_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_answer_advgroup1`
    FOREIGN KEY (`group_id`)
    REFERENCES `ushauri2`.`advgroup` (`group_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ushauri2`.`user` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Answers to a question';


-- -----------------------------------------------------
-- Table `ushauri2`.`questionanswer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`questionanswer` (
  `group_id` VARCHAR(12) NOT NULL,
  `member_id` VARCHAR(45) NOT NULL,
  `question_id` VARCHAR(12) NOT NULL,
  `answer_group` VARCHAR(12) NOT NULL,
  `answer_id` VARCHAR(12) NOT NULL,
  `answer_sent` INT(1) NULL,
  PRIMARY KEY (`group_id`, `member_id`, `question_id`, `answer_group`, `answer_id`),
  INDEX `fk_questionanswer_answer1_idx` (`answer_group` ASC, `answer_id` ASC),
  CONSTRAINT `fk_questionanswer_question1`
    FOREIGN KEY (`group_id` , `member_id` , `question_id`)
    REFERENCES `ushauri2`.`question` (`group_id` , `member_id` , `question_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questionanswer_answer1`
    FOREIGN KEY (`answer_group` , `answer_id`)
    REFERENCES `ushauri2`.`answer` (`group_id` , `answer_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ushauri2`.`answeraudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`answeraudio` (
  `group_id` VARCHAR(12) NOT NULL,
  `answer_id` VARCHAR(12) NOT NULL,
  `audio_id` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`group_id`, `answer_id`, `audio_id`),
  INDEX `fk_answeraudio_audio1_idx` (`audio_id` ASC),
  CONSTRAINT `fk_answeraudio_answer1`
    FOREIGN KEY (`group_id` , `answer_id`)
    REFERENCES `ushauri2`.`answer` (`group_id` , `answer_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answeraudio_audio1`
    FOREIGN KEY (`audio_id`)
    REFERENCES `ushauri2`.`audio` (`audio_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ushauri2`.`questiontag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ushauri2`.`questiontag` (
  `group_id` VARCHAR(12) NOT NULL,
  `member_id` VARCHAR(45) NOT NULL,
  `question_id` VARCHAR(12) NOT NULL,
  `tag_name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`group_id`, `member_id`, `question_id`, `tag_name`),
  CONSTRAINT `fk_questiontag_question1`
    FOREIGN KEY (`group_id` , `member_id` , `question_id`)
    REFERENCES `ushauri2`.`question` (`group_id` , `member_id` , `question_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
